name: LedgerFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build, Lint & Test (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint with Ruff
        run: ruff check .

      - name: Run Docker Compose tests
        run: |
          docker compose build
          docker compose up -d
          sleep 15
          docker compose run --rm test-runner pytest -v --cov=. --cov-report=term-missing --cov-report=html
          docker compose down -v --remove-orphans

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/